import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRightIcon } from "@/components/site/Icons";
import { TeamCard } from "@/components/site/TeamCard";
import { currentTeam, futureRoles, method } from "@/data/site";

export const metadata: Metadata = { title: "Method & Company", description: "Como a AZLO entende, desenha, constrói e opera sistemas para contextos reais.", alternates: { canonical: "/sobre" }, openGraph: { title: "Method & Company | AZLO", description: "Como a AZLO entende, desenha, constrói e opera sistemas para contextos reais.", url: "/sobre" } };

export default function AboutPage() {
  return <main id="main" className="company-page"><section className="page-hero page-hero--dark"><div className="page-hero__grid" aria-hidden="true" /><div className="site-frame"><p className="breadcrumb mono-label">AZLO / COMPANY</p><p className="eyebrow eyebrow--light"><span />METHOD / RESPONSIBILITY</p><h1>Projetar para a realidade é uma escolha de <em>engenharia.</em></h1><p>A AZLO trabalha entre software, infraestrutura, dados e saúde. A medida é simples: o sistema precisa ser entendível, operável e responsável.</p></div></section><section className="section section--light"><div className="site-frame"><div className="section-heading section-heading--split"><div><p className="eyebrow"><span />METHOD</p><h2>Contexto antes de <em>ferramenta.</em></h2></div><p>Uma sequência curta para transformar um problema em sistema operável, com responsabilidades visíveis.</p></div><ol className="method-rail method-rail--large">{method.map((item) => <li key={item.number}><span>{item.number} / {item.label}</span><h3>{item.title}</h3><p>{item.text}</p></li>)}</ol></div></section><section className="section team-section" id="team"><div className="site-frame"><div className="section-heading section-heading--split"><div><p className="eyebrow"><span />CURRENT TEAM</p><h2>Pessoas próximas do <em>problema.</em></h2></div><p>Quem projeta e responde pelo sistema permanece visível no trabalho.</p></div><div className="team-grid">{currentTeam.map((member) => <TeamCard key={member.name} member={member} />)}</div><div className="future-team"><p className="eyebrow"><span />OPEN / FUTURE ROLES</p><h2>Expansão em discussão, não vagas abertas.</h2><div className="team-grid">{futureRoles.map((member) => <TeamCard key={member.name} member={member} />)}</div></div><Link className="section-link" href="/contato">Falar com a AZLO <ArrowRightIcon /></Link></div></section></main>;
}
