import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRightIcon } from "@/components/site/Icons";
import { services } from "@/data/site";

export const metadata: Metadata = { title: "Engenharia", description: "Sistemas clínicos, IA integrada, infraestrutura, dados e automação para operações reais.", alternates: { canonical: "/servicos" }, openGraph: { title: "Engenharia | AZLO", description: "Sistemas clínicos, IA integrada, infraestrutura, dados e automação para operações reais.", url: "/servicos" } };

export default function ServicesPage() {
  return <main id="main" className="engineering-page"><section className="page-hero page-hero--dark"><div className="page-hero__grid" aria-hidden="true" /><div className="site-frame"><p className="breadcrumb mono-label">AZLO / ENGINEERING</p><p className="eyebrow eyebrow--light"><span />ENGENHARIA DE SISTEMAS</p><h1>Intervenções que começam pelo <em>ambiente.</em></h1><p>Organizamos a atuação pelo que precisa mudar na operação — e usamos tecnologia como meio, não como produto isolado.</p><Link className="button button--primary page-hero__cta" href="/contato">Descrever um problema <ArrowRightIcon /></Link></div></section><section className="section section--light"><div className="site-frame"><div className="section-heading"><p className="eyebrow"><span />MÓDULOS DE ENGENHARIA</p><h2>Quatro camadas para fazer o sistema <em>operar.</em></h2></div><div className="engineering-grid engineering-grid--page">{services.map((service) => <article className="engineering-module" key={service.index}><span className="engineering-module__number">{service.index}</span><p className="mono-label">{service.module}</p><h3>{service.title}</h3><p>{service.intervention}</p><ul>{service.capabilities.map((capability) => <li key={capability}>{capability}</li>)}</ul><a href={`mailto:contato@azlo.com.br?subject=${encodeURIComponent(service.nextStep)}`}>{service.nextStep} <ArrowRightIcon /></a></article>)}</div></div></section><section className="section engineering-principles"><div className="site-frame"><div className="section-heading section-heading--split"><div><p className="eyebrow eyebrow--light"><span />LIMITES</p><h2>Contexto antes de <em>ferramenta.</em></h2></div><p>LLMs, agentes, RAG, bancos vetoriais, APIs, VPS e pipelines fazem parte do repertório. A escolha depende dos dados, permissões, infraestrutura e manutenção que o contexto suporta.</p></div><ul className="principle-rail"><li><span>01</span><strong>Observe</strong><p>Leia fluxo, sinais e impacto antes de intervir.</p></li><li><span>02</span><strong>Preserve</strong><p>Priorize consentimento, segurança, continuidade e reversibilidade.</p></li><li><span>03</span><strong>Opere</strong><p>Entregue uma mudança que possa ser mantida e compreendida.</p></li></ul></div></section></main>;
}
